### ISSUE TITLE
Tests show macros are slightly broken

### ISSUE THREAD

**Issue by Mikolaj** [LambdaHack/LambdaHack#189]
@rszczers: uh, oh, manual tests (sadly there are no automatic UI tests yet) show some breakage.

This macro (bound to `]`)

https://github.com/LambdaHack/LambdaHack/blob/b7d9a803782c3844fefa040a0514d41833dd2672/engine-src/Game/LambdaHack/Client/UI/Content/Input.hs#L218

works fine, but violates the data invariant. I suppose we can just allow macro recording keys inside macros, after revisiting why we disallowed that.

However, this macro (bound to `[`)

https://github.com/LambdaHack/LambdaHack/blob/b7d9a803782c3844fefa040a0514d41833dd2672/engine-src/Game/LambdaHack/Client/UI/Content/Input.hs#L215

doesn't work. It just repeats the previously recorded macro, not the exploration command. There are some ways of fixing that, which are easier to find now, after we've refactored the code, but some brainstorming is required to choose the best way.

**Comment by rszczers** [comment]
It looks like I've opened the pandora's box: all the macros that end with a variant of `v` behave quite different now. At first glance I was quite amazed that those macros worked at all. Then I realized the purpose of `C-V` is in fact to repeat 25 times the last player's action. So, figuratively speaking, it's something like a bulldozer mode.

Since we've got now a complete separate buffer where we keep last action and we can redo it by invoking `RepeatLast`, maybe what we need to do is to extend this constructor to `RepeatLast Int` and bind this to `C-V`? It's a matter of choice now, if we want `C-V` to repeat the whole macro or just the last action. To follow the convention, maybe we should put `A-V` in place of all `C-V`s, since `A-v` stands for `RepeatLast`?

I need to put some more though into this.

**Comment by Mikolaj** [comment]
These are valid brainstorming ideas. To repeat my diagnosis: all the macros from content worked fine before and all similar to the first one I cited still work fine and that is because `C-V` repeated and still repeats the whole last macro. The problem is only that previously last non-quote key (pressed or from content) was always overwriting the recorded macro (which was obviously wrong for in-game macros), but this has been fixed by you. In short, the functionality was built up starting from an incorrect behaviour. :)

**Comment by rszczers** [comment]
New idea: I think we could benefit by having a stack of macros. In-game macros would operate only on the bottom of the stack (i.e. player still wouldn't be allowed to define nested in-game macros), while predefined macros had to be parsed. The idea is to push empty macro buffer to the stack whenever we start a macro inside a macro, and pop it when we are done.

**Comment by Mikolaj** [comment]
This is a sensible solution to the problem that we can't have `Record` in macros created in-game by the player. Is it the problem real though? Is `Record` breaking anything if it appears there, or is it just that it can't be entered by the player, so it never appears? Narrowing the type (by type definition or by informal data invariant) not to have values that can't be represented is always welcome, but it's not mandatory and, in fact, often we have wider types, e.g, balanced trees represented in the type of arbitrary tress that undergo balancing after some operations, so the data invariants holds only in some cases.

**Comment by rszczers** [comment]
Well, I missed out that we're constrained to one level deep macros. The stack would require us to have two separate commands, the one for starting and the other for ending the recording mode. Otherwise it's pointless. Let's forget about it.

What we're really lacking of is a way of interpreting `Record` when `smacroBuffer` has `Right` values. IIRC they are completely ignored right now (and that's why the trick with `RepeatLast 1` worked out). So, how about extending `smacroBuffer` once more, this time from `Either` to something like [`These`](https://hackage.haskell.org/package/these-1.0.1/docs/Data-Functor-These.html)? There's general pattern emerging. Aren't those value constructors representing in-game modes?

The downside of this solution is that we would need to rewrite `Right` values and hold them in a new middle value each time we replay a predefined macro in order to not lose the in-game macro. Also, I'm not quite sure what would happen if we tried to replay a predefined macro when recording the in-game one.

**Comment by Mikolaj** [comment]
Interesting thoughts. I will need to ponder in peace. In principle, I'm not against a stack even if if ever only use two at most two levels of it. That's probably similar to `These` and better than two separate macro buffers: for in-game and for config/content. Each option is on the table, however.

**Comment by Mikolaj** [comment]
I thought about it for a bit and I think you nailed it here: "we're really lacking of is a way of interpreting Record when repeating a macro". If we wanted `Record` to always just record a macro in `smacroBuffer`, we see the following. Whenever the player records a macro, the commands are at once executed when they enter `smacroBuffer`. However, if any of the command is macro recording, it trashes `smacroBuffer` immediately when it executes. So the starting part of the macro being recorded by player is lost. That's probably why the original implementation of recording macros was broken, at least in that recording complex macros didn't work. Did I capture your diagnosis well?

Moreover, macros may be arbitrarily nested. If key 'v' is bound to repeat-macro-once, 'a' is bound to [', b, c, ', v] and 'c' is bound to [', a, a, a, ', v] then we have infinitely nested macro (no idea if it would do anything or just loop in unwinding). Therefore I think we need a stack of macro recording buffers (not of macro-replaying buffers, because new macros are correctly unwound and added to the macro-replaying buffer, so that part works). The macro replay command would always replay from one level deeper macro recording buffer. I don't know when, if ever, we can GC a level of the stack. Probably when we run commands from level n, we can GC levels n+1 and all deeper as soon as we encounter a macro recording command (on level n).

Do I make sense?

**Comment by rszczers** [comment]
> However, if any of the command is macro recording, it trashes smacroBuffer immediately when it executes.

That's right. There's an ambiguity between in-game macros and predefined ones that interleave each other: predefined ones are placed all at once in `slastPlay`, no matter what, and from there they are consumed individually by `promptGetKey` as user's actions. When stumbling upon `Record`, `cmdHumanSem` fires up `recordHuman` where we're switching `smacroBuffer` from `Left` to `Right`, or in the other way, accordingly. So, in result of lacking separate macro buffer, starting part of in-game macro could get lost, as you said.

> That's probably why the original implementation of recording macros was broken, at least in that recording complex macros didn't work. 

Previously the macro buffer was trashed after every user's action, even when the action was to repeat the macro. It was so, since last action's buffer and macro buffer were shared. So macros defined with predefined macros were repeated at most once. Most of use-cases of predefined macros is repeating them 25 or 100 times. After macro got repeated, what we're left with in macro buffer was the last action from macro that was defined in predefined macro. In result we were repeating last action most of the time.

> If key 'v' is bound to repeat-macro-once, 'a' is bound to [', b, c, ', v] and 'c' is bound to [', a, a, a, ', v] then we have infinitely nested macro (no idea if it would do anything or just loop in unwinding).

Right. So, syntactically speaking, we constrain definitions to be one-level deep. (Here comes a brain dump, consider skip reading it ;-)) For the sake of comparison, let's consider we have one additional state with extra buffer that we use only when replaying. When `a` pressed,  `[', b, c, ', v]` is added at once to `slistPlay`.  So, we would record `b` and then, proceeding with `c`, we would add once again `[', b, c, ', v]` to `slistPlay`. Then we would take second loop and never finally reach the end doing only `b`'s. This take uses only the extra macro buffer, but with cost of `slistPlay` growing infinitely. The idea with stack of `smacroBuffer` seems to share the same flaw, but it's more natural. Especially, if choosing to extend `Either`, we would land with some kind of unidiomatic monstrosity, like `These [K.KM] KeyMacro ExtraKeyMacro` where `ExtraKeyMacro` would be yet another wrapper around `KeyMacro` with old and extra macro in it. Sure, we could store those values directly in `SessionUI`, but it seems buggy overall. Yuck.

So I'm in a favor of a stack, but let's take some time to look around for a better solution.

**Comment by Mikolaj** [comment]
I think we could use just a list as a stack: smacroBuffer :: `[Either [K.KM] KeyMacro]`. Let try to execute the example macro using this implementation of `smacroBuffer`.

The user presses `a` and `slistPlay` becomes (ignoring the newtype) `[', b, c, ', v]`. Quote character is processed, so recording is started, `b` is executed (say, it displays a dot on the screen) and `smacroBuffer` is `[Left [b]]`. Then `c` is executed, which is a macro replay command, so now `slistPlay` becomes `[', a, a, a, ', v, ' v]` and  `smacroBuffer` is `[Right [], Left [b]]`. Because the top of the stack is `Right`, quote starts recording another macro (and not finishes the previous macro), so `smacroBuffer` is `[Left [], Left [b]]`. Now `a` is executed, which is a macro replay command, so `slistPlay` becomes `[', b, c, ', v, a, a, ', v, ' v]` and  `smacroBuffer` is `[Right [], Left[], Left [b]]`. Another quote makes `smacroBuffer` is `[Left [], Left[], Left [b]]`. Then another dot is placed on the screen with `b` and `smacroBuffer` is `[Left [b], Left[], Left [b]]`. Etc. We can't show how stack unwinding works, because it never gets there. :) But it should work somehow.

The problems that we have with the ambiguoes recording start/stop command is probably why it's never used in symbolic languages, but at most in kitchen appliances. But it's fun. :)

**Comment by rszczers** [comment]
Ugh, it's not so easy-peasy in finite case. For example, let `x` be a terminal, `a` := `[',x,']`, `b` := `[',a,']`. Here's how this is supposed to work (modulo in-game buffer):

| # | Input | slastPlay   | smacroBuffer |
| - |-------| ----------- | ------------ |
| 1 |`b`    |`[', a, '] ` | `[]`
| 2 |`'`    |`[a, ']    ` | `[Left []]`
| 3 |`a`    |`[',x,','] ` | `[Left [a]]`
| 4 |`'`    |`[x,',']   ` | `[Left [], Left [a]]`
| 5 |`x`    |`[',']     ` | `[Left [x], Left [a]]`
| 6 |`'`    |`[']       ` | `[Right [x], Left [a]]`
| 7 |`'`    |`[]        ` | `[Right [a]]`

Steps 3-4 involve doing some context-dependent processing beforehand. Also, there's a lot of ill cases, like `[',x,',',x,']`, that we either don't want to be accepted, or we want to handle them like `(x)(x)`.

**Comment by Mikolaj** [comment]
According to my example, the macro replay command `a` in step 3 should leave `smacroBuffer` with content `[Right [], Left [a]]` and there is nothing particularly context dependent about that. Then in step 4 we have `Right` at the top of the stack, so we interpret quote as macro recording start, without any trickery and get the result you've written.

And indeed the action on the screen done by `[',x,',',x,']` is equal to that of `[x,x]` and there's nothing wrong about it. However, for `[',x,',',x,',v]` it's `[x,x,x]` and it's also the same as `[x,',x,',v]`. That's what I said about GC of unreachable macros (the first recorded x).

**Comment by Mikolaj** [comment]
I've encoded all macro tests from this issue and they pass, so let's move the discussion to the main issue about macros #161.
