### ISSUE TITLE
dungeonFlavourMap could be self-documenting

### ISSUE THREAD

**Issue by jafristr** [LambdaHack/LambdaHack#274]
- [x] maxBound -> invalidFlavourCode
- [x] uFlav0 -> flavourMapFromPreviousGame
- [ ] Word16 -> FlavourEnum [edit: also in other places, mutatis mutandis]

- [ ] Maybe even PointI -> PointEnum?

**Comment by Mikolaj** [comment]
The main parts of this are now implemented by Jamie and me and, looking at `keepMetaGameInformation`, I'm having second thoughts about adding aliases for types that are `Enum` codes for other types. I wouldn't be able to use the aliases in `keepMetaGameInformation`, because it's common for two use cases (same codes, different main types). Closing for now.
