### ISSUE TITLE
Objects leave trails when they move

### ISSUE THREAD

**Issue by Soupstraw** [LambdaHack/LambdaHack#281]
The trails can be seen on the image. When I resize the game window, the trails disappear. 

![12-11-2021_18:10](https://user-images.githubusercontent.com/6863341/141498625-f4fc7391-191c-446e-9455-3db0bbbd8786.png)

It seems like the boxes around the objects are not perfectly box-shaped and the overhanging part does not get cleared from the screen in between window updates.

I am playing the game on full screen at 1920x1080 resolution.

**Comment by Mikolaj** [comment]
Thank you so much for the report. Which version number of the game is that? This is SDL frontend from what I see?

**Comment by Soupstraw** [comment]
Yes, that's the SDL frontend. The version is `0.10.3.0`.

**Comment by Mikolaj** [comment]
I need your help reproducing that, because this is impossible. ;)

Which OS is that? How did you obtain the game's executable? Did you get fullscreen from commandline option or from `~/.LambdaHack/config.ui.ini`? Did you also set `--allFontsScale 1.5` (or `allFontsScale = 1.5` in config file)?

Any idea why the fonts on your screenshot are rectangular instead of square?

Anything else special with your system?

Could you try changing `chosenFontset = "dejavuBold"` in your config file to `chosenFontset = "dejavuBold_original"` and then to  `chosenFontset = "binary"`?

**Comment by Soupstraw** [comment]
I'm running on Arch Linux using `bspwm` as my window manager. To get to fullscreen, I just made the window go to fullscreen using the fullscreen command in my wm. I got the executable as a binary from the releases tab in Github (`LambdaHack_0.10.3.0_ubuntu-16.04-amd64.tar.gz`).

I also tried setting the `allFontsScale` argument to 1.5 and then changing the fullscreen mode to both `BigBorderlessWindow` and `ModeChange`, but the overhanging part of the boxes still showed and left trails. I also tried to set the `chosenFontset` to both of your suggested options but to no avail.

Also, this bug does not seem to disappear, when I make the game start in a floating window, so it might not even be related to the game running in fullscreen.

**Comment by Mikolaj** [comment]
Thank you for the tests. That eliminates most suspects. I swear this must be an SDL2 bug, because I'm literally calling SDL's "rectangle" function there. Or even an OpenGL driver bug. Which version of `libsdl2-2.0-0` (or a similar name) do you have?

At this point I'm out of ideas. Perhaps updating SDL2 or your video card driver would help? Perhaps compiling on your machine? The version you use works for me(TM) on my Ubuntu with old libsdl2-2.0-0 and on newest stable Debian with new libsdl2-2.0-0.

Not much hope, but perhaps the version compiled by CI would fare differently, since it uses a newish Ubuntu, not my ancient 16.04:

https://github.com/LambdaHack/LambdaHack/suites/4199574071/artifacts/108500219

(this is from run https://github.com/LambdaHack/LambdaHack/actions/runs/1398631179)

or, there is a version of Allure of the Stars compiled by CI for Ubuntu 18.04, which is mid-way:

https://github.com/AllureOfTheStars/Allure/suites/4197807308/artifacts/108417870

(taken from https://github.com/AllureOfTheStars/Allure/actions/runs/1397959810).

Thank you again!

**Comment by Mikolaj** [comment]
Possibly related, because that's exactly the function I use, but that would suggest a very new SDL2 libs:

https://discourse.libsdl.org/t/sdl-renderdrawrect-function-broken/28756

**Comment by Soupstraw** [comment]
Yep, I seem to be using SDL 2.0.16.0, that's interesting to know.

**Comment by Mikolaj** [comment]
If I get a confirmation SDL is really to blame, I will have to work around by drawing 4 lines instead of a rectangle (despite the four lines reportedly producing some artifacts), because there's no way I can persuade Debian and Homebrew and Windows/pacman and Nix to skip 2.0.16 (and probably 2.0.17 as well). The upside is that CI dev version snapshots with work fine for you and for anybody else running bleeding edge libs.

**Comment by Mikolaj** [comment]
I've just tried the workaround with 4 lines instead of a rectangle, but it fails in my SDL2 2.0.4, so I commented it out. I've attempted a different workaround, probably ineffective, but that's the only thing that also works on old SDL2 versions: 

https://github.com/LambdaHack/LambdaHack/commit/2f5caa017e6b071740727dc11a10ab378405900d#diff-476d1b48fb4f51f25506cf3dcc7f6c60640541e4d2b5d22ededb559b9b6e5b05R515

You can try it from CI here

https://github.com/LambdaHack/LambdaHack/actions/runs/1459931173

or here

https://github.com/AllureOfTheStars/Allure/actions/runs/1459932071

**Comment by Mikolaj** [comment]
And here is one last workaround attempt that overwrites the colorful rectangle with a black rectangle, so even though the rectangle has a broken shape, with some luck it should not leave artifacts behind: https://github.com/LambdaHack/LambdaHack/actions/runs/1461088386

**Comment by Soupstraw** [comment]
Yep, at least the trails are gone now on my machine on both versions. The boxes still don't look like boxes, but I can live with that. Hopefully the new SDL version will be out soon :)

**Comment by Mikolaj** [comment]
Great. Thank you again. So this workaround will remain in LambdaHack and Allure v0.11, which is feature-complete now, but will take some weeks or months to playtest and balance.

**Comment by Mikolaj** [comment]
@Soupstraw: v0.11.0.0 is released with this workaround baked in and I also noticed my windows binaries have libsdl2 2.0.18, the same in Debian unstable, and I can't see the deformation there, so it seems the SDL2 fix and its adoption was rather prompt this time. However, in the distro releases that happen to stabilize on 2.0.16, the bug will remain forever.

Thank you again for the report and for the testing.
